name: servedir # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple HTTP server for static files # 79 char long summary
description: |
  Run simple HTTP server for static files on working directory.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

parts:
  servedir:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    go-importpath: github.com/jempe/servedir
apps:
  servedir:
    command: servedir
